# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  pull_request:
    types: [ closed ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  delete_stack:
    name: Delete testing stack
    runs-on: ubuntu-latest

    steps:

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: try to delete stack on testing
      env:
        LAMBDA_NAME: ${{ secrets.LAMBDA_NAME }}
        STACK_PREFIX: ${{ secrets.STACK_PREFIX }}
      run: |
        PR_NUMBER=$(echo "$GITHUB_REF" | awk -F / '{print $3}')
        stack_name="$STACK_PREFIX-$PR_NUMBER"
        payload="{ \"stackName\": \"$stack_name\" }"
        aws lambda invoke --function-name $LAMBDA_NAME --payload "$payload" response.json
        exit 0