AWSTemplateFormatVersion: "2010-09-09"
Description: AZ resources

Parameters:
  Vpc:
    Description: "VPC identifier."
    Type: AWS::EC2::VPC::Id
  Range:
    Description: "CIDR Range digit subnet 10.0.X0.0/24 "
    Type: String
  CidrBlockPrefix:
    Description: "Vpc Cidr Prefix of two first digit X.X.0.0/16"
    Type: String
  AvailabilityZone:
    Description: "Subnets Availability Zone"
    Type: AWS::EC2::AvailabilityZone::Name
  PublicNetworkAclId:
    Description: "Public Network ACL ID"
    Type: String
  PublicRouteTableId:
    Description: "Public Route Table"
    Type: String
  PrivateNetworkAclId:
    Description: "Private Network ACL ID"
    Type: String
  PrivateRouteTableId:
    Description: "Private Route Table"
    Type: String
  RunNat:
    Description: Run Nat Gateway for each Private Zone
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Conditions:
  RunNat: !Equals [ !Ref RunNat, 'true' ]

Resources:
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Sub "${CidrBlockPrefix}.${Range}0.0/24"
      VpcId: !Ref Vpc
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: network
          Value: public
        - Key: Name
          Value: !Sub "subnet-public-${Range}"

  PublicSubnetAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      NetworkAclId: !Ref PublicNetworkAclId

  PublicRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTableId

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: !Sub "${CidrBlockPrefix}.${Range}1.0/24"
      VpcId: !Ref Vpc
      AvailabilityZone: !Ref AvailabilityZone
      Tags:
        - Key: network
          Value: private
        - Key: Name
          Value: !Sub "subnet-private${Range}"

  PrivateSubnetAclAssociation:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      NetworkAclId: !Ref PrivateNetworkAclId

  PrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTableId

  NatGateway:
    Type: AWS::CloudFormation::Stack
    Condition: RunNat
    Properties:
      TemplateURL: nat.yml
      Parameters:
        Vpc: !Ref Vpc
        PublicSubnetId: !Ref PublicSubnet
        PrivateRouteTable: !Ref PrivateRouteTableId

Outputs:
  AvailabilityZone:
    Description: "Availability Zone"
    Value: !Ref AvailabilityZone
  PublicSubnet:
    Description: "Public Subnet"
    Value: !Ref PublicSubnet
  PrivateSubnet:
    Description: "Private Subnet"
    Value: !Ref PrivateSubnet
